import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import axios from 'axios';
dotenv.config();
const app=express(); app.use(cors({origin:process.env.CLIENT_URL||'*'})); app.use(express.json());
const upload=multer({dest:'uploads/'});
const User=mongoose.model('User',new mongoose.Schema({name:String,email:{type:String,unique:true},password:String,role:{type:String,default:'student'},profile:Object},{timestamps:true}));
const Scholarship=mongoose.model('Scholarship',new mongoose.Schema({title:String,provider:String,description:String,amount:Number,deadline:Date,eligibility:Object,tags:[String],active:{type:Boolean,default:true}},{timestamps:true}));
const Application=mongoose.model('Application',new mongoose.Schema({user:{type:mongoose.Schema.Types.ObjectId,ref:'User'},scholarship:{type:mongoose.Schema.Types.ObjectId,ref:'Scholarship'},status:{type:String,default:'submitted'},documents:[String]},{timestamps:true}));
const Document=mongoose.model('Document',new mongoose.Schema({user:{type:mongoose.Schema.Types.ObjectId,ref:'User'},name:String,path:String,type:String},{timestamps:true}));
const sign=u=>jwt.sign({id:u._id,role:u.role},process.env.JWT_SECRET||'dev-secret',{expiresIn:'7d'});
const auth=(req,res,next)=>{try{const h=req.headers.authorization||'';req.user=jwt.verify(h.replace('Bearer ',''),process.env.JWT_SECRET||'dev-secret');next()}catch{return res.status(401).json({message:'Authentication required'})}};
const admin=(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({message:'Admin only'});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'scholarship-api'}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});const exists=await User.findOne({email});if(exists)return res.status(409).json({message:'Email already registered'});const user=await User.create({name,email,password:await bcrypt.hash(password,10),profile:{}});res.status(201).json({token:sign(user),user:{id:user._id,name,email,role:user.role}})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/auth/login',async(req,res)=>{const user=await User.findOne({email:req.body.email});if(!user||!(await bcrypt.compare(req.body.password,user.password)))return res.status(401).json({message:'Invalid credentials'});res.json({token:sign(user),user:{id:user._id,name:user.name,email:user.email,role:user.role}})});
app.get('/api/scholarships',async(req,res)=>{const q=req.query.q||'';const filter={active:true,...(q?{$or:[{title:new RegExp(q,'i')},{provider:new RegExp(q,'i')},{tags:new RegExp(q,'i')}]}:{})};res.json(await Scholarship.find(filter).sort({deadline:1}))});
app.post('/api/scholarships',auth,admin,async(req,res)=>res.status(201).json(await Scholarship.create(req.body)));
app.put('/api/scholarships/:id',auth,admin,async(req,res)=>res.json(await Scholarship.findByIdAndUpdate(req.params.id,req.body,{new:true})));
app.delete('/api/scholarships/:id',auth,admin,async(req,res)=>{await Scholarship.findByIdAndUpdate(req.params.id,{active:false});res.json({ok:true})});
app.post('/api/applications',auth,async(req,res)=>{const a=await Application.create({user:req.user.id,scholarship:req.body.scholarship,documents:req.body.documents||[]});res.status(201).json(a)});
app.get('/api/applications/me',auth,async(req,res)=>res.json(await Application.find({user:req.user.id}).populate('scholarship')));
app.post('/api/documents',auth,upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({message:'File required'});res.status(201).json(await Document.create({user:req.user.id,name:req.file.originalname,path:req.file.path,type:req.file.mimetype}))});
app.get('/api/documents',auth,async(req,res)=>res.json(await Document.find({user:req.user.id}).sort({createdAt:-1})));
app.post('/api/recommendations',auth,async(req,res)=>{try{const r=await axios.post(`${process.env.ML_SERVICE_URL||'http://127.0.0.1:8000'}/recommend`,req.body);res.json(r.data)}catch{res.json({recommendations:(req.body.scholarships||[]).slice(0,10).map((s,i)=>({...s,score:Math.max(.1,1-i*.05)}))})}});
app.get('/api/admin/stats',auth,admin,async(req,res)=>res.json({users:await User.countDocuments(),scholarships:await Scholarship.countDocuments({active:true}),applications:await Application.countDocuments(),documents:await Document.countDocuments()}));
const start=async()=>{await mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/scholarship_db');app.listen(process.env.PORT||5000,()=>console.log('API running'))};
start().catch(console.error);
